### ISSUE TITLE
What arguments does Robots.parse() take?

### ISSUE THREAD

**Issue by kittenswolf** [seomoz/reppy#70]
```
from reppy.robots import Robots
rp = Robots.parse()
```

... what arguments does Robots.parse() take?
I want to a robots.txt file passed in as a string. How is that possible?

**Comment by b4hand** [comment]
You can see an example of the arguments passed to `Robots.parse` here:

https://github.com/seomoz/reppy/blob/02e4588ac2fba459859aaf1b0d6c30808adc94f8/tests/test_robots.py#L74-L84

It takes a URL and then a string for the `robots.txt` file. The URL is required in order to interpret the context for relative URLs inside of the `robots.txt` file.
